In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.impute import SimpleImputer

In [2]:
sample_submission_df=pd.read_csv("/kaggle/input/competitions/mlp-term-1-2026-kaggle-assignment-1/sample_submission.csv")
test_df=pd.read_csv("/kaggle/input/competitions/mlp-term-1-2026-kaggle-assignment-1/test.csv")
train_df=pd.read_csv("/kaggle/input/competitions/mlp-term-1-2026-kaggle-assignment-1/train.csv")

In [3]:
sample_submission_df.head()

   id  total_amount
0   0         24.46
1   1         24.37
2   2         19.88
3   3         25.02
4   4         22.25

In [4]:
test_df.head()

,id,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,congestion_surcharge,Airport_fee
0,0,1,2023-06-30 20:48:10,2023-06-30 21:49:13,1.0,1.57,1.0,N,161,92,Cash,1.0,2.486622,0.0,1.0,2.5,0.0
1,1,0,2023-06-29 10:58:03,2023-06-29 12:00:43,1.0,2.80,1.0,N,145,209,Credit Card,2.5,6.627894,0.0,1.0,2.5,0.0
2,2,1,2023-06-30 13:57:25,2023-06-30 13:41:32,1.0,2.53,1.0,N,221,187,Credit Card,0.0,7.958300,0.0,1.0,2.5,0.0
3,3,1,2023-06-30 03:20:58,2023-06-30 04:04:18,1.0,2.51,1.0,N,100,142,Cash,1.0,4.815220,0.0,1.0,2.5,0.0
4,4,1,2023-06-29 11:27:35,2023-06-29 10:48:37,1.0,0.36,1.0,N,199,257,Credit Card,0.0,5.788000,0.0,1.0,2.5,0.0

In [5]:
train_df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,0,2023-06-28 17:31:46,2023-06-28 18:22:12,1.0,1.50,1.0,N,212,237,Credit Card,5.0,6.533210,0.0,1.0,24.80,2.5,0.0
1,0,2023-06-29 19:15:55,2023-06-29 19:07:31,1.0,3.80,1.0,N,6,163,Credit Card,5.0,9.187048,0.0,1.0,31.55,2.5,0.0
2,1,2023-06-30 18:28:50,2023-06-30 18:01:19,2.0,1.89,1.0,N,35,81,Credit Card,2.5,6.793777,0.0,1.0,24.84,2.5,0.0
3,1,2023-06-30 22:57:37,2023-06-30 22:55:34,1.0,1.10,1.0,N,46,99,Credit Card,1.0,3.695121,0.0,1.0,13.45,2.5,0.0
4,1,2023-06-28 18:39:16,2023-06-28 17:31:29,2.0,2.84,1.0,N,213,114,Credit Card,2.5,7.838753,0.0,1.0,29.88,2.5,0.0

In [6]:
cols=train_df.columns.tolist()

In [7]:
train_df=train_df.fillna(0)

In [8]:
train_df.isna().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
extra                    0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
dtype: int64

In [9]:
numeric_cols=['passenger_count',  'congestion_surcharge', 'Airport_fee']
si_num=SimpleImputer(strategy='mean',missing_values=0)
train_df[numeric_cols]=si_num.fit_transform(train_df[numeric_cols])
train_df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,0,2023-06-28 17:31:46,2023-06-28 18:22:12,1.000000,1.50,1.0,N,212,237,Credit Card,5.0,6.533210,0.0,1.0,24.80,2.500000,1.707646
1,0,2023-06-29 19:15:55,2023-06-29 19:07:31,1.000000,3.80,1.0,N,6,163,Credit Card,5.0,9.187048,0.0,1.0,31.55,2.500000,1.707646
2,1,2023-06-30 18:28:50,2023-06-30 18:01:19,2.000000,1.89,1.0,N,35,81,Credit Card,2.5,6.793777,0.0,1.0,24.84,2.500000,1.707646
3,1,2023-06-30 22:57:37,2023-06-30 22:55:34,1.000000,1.10,1.0,N,46,99,Credit Card,1.0,3.695121,0.0,1.0,13.45,2.500000,1.707646
4,1,2023-06-28 18:39:16,2023-06-28 17:31:29,2.000000,2.84,1.0,N,213,114,Credit Card,2.5,7.838753,0.0,1.0,29.88,2.500000,1.707646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,2023-06-28 16:38:27,2023-06-28 17:02:20,1.000000,3.31,1.0,N,201,55,Cash,2.5,2.195433,0.0,1.0,22.10,2.500000,1.707646
9996,1,2023-06-30 15:59:37,2023-06-30 17:43:59,1.000000,1.22,1.0,N,221,143,Credit Card,2.5,9.137115,0.0,1.0,21.45,2.500000,1.707646
9997,1,2023-06-29 09:26:14,2023-06-29 11:22:26,1.000000,1.31,1.0,N,161,150,Credit Card,0.0,5.940952,0.0,1.0,17.29,2.500000,1.707646
9998,1,2023-06-30 17:43:41,2023-06-30 17:46:22,1.000000,0.89,1.0,N,120,191,Cash,2.5,3.233409,0.0,1.0,13.70,2.500000,1.707646
9999,1,2023-06-29 21:54:57,2023-06-29 22:25:39,1.382095,0.64,0.0,0,111,36,Wallet,0.0,3.674585,0.0,1.0,14.25,2.451683,1.707646

In [10]:
train_df.store_and_fwd_flag.unique()

array(['N', 0, 'Y'], dtype=object)

In [11]:
train_df['store_and_fwd_flag']=train_df['store_and_fwd_flag'].replace(0,'N')
train_df.store_and_fwd_flag.unique()

array(['N', 'Y'], dtype=object)

In [12]:
test_df=test_df.fillna(0)

In [13]:
test_df.isna().sum()

id                       0
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
extra                    0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
congestion_surcharge     0
Airport_fee              0
dtype: int64

In [14]:
numeric_cols=['passenger_count',  'congestion_surcharge', 'Airport_fee']
si_num=SimpleImputer(strategy='mean',missing_values=0)
test_df[numeric_cols]=si_num.fit_transform(test_df[numeric_cols])
test_df

,id,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,congestion_surcharge,Airport_fee
0,0,1,2023-06-30 20:48:10,2023-06-30 21:49:13,1.0,1.57,1.0,N,161,92,Cash,1.0,2.486622,0.0,1.0,2.500000,1.630137
1,1,0,2023-06-29 10:58:03,2023-06-29 12:00:43,1.0,2.80,1.0,N,145,209,Credit Card,2.5,6.627894,0.0,1.0,2.500000,1.630137
2,2,1,2023-06-30 13:57:25,2023-06-30 13:41:32,1.0,2.53,1.0,N,221,187,Credit Card,0.0,7.958300,0.0,1.0,2.500000,1.630137
3,3,1,2023-06-30 03:20:58,2023-06-30 04:04:18,1.0,2.51,1.0,N,100,142,Cash,1.0,4.815220,0.0,1.0,2.500000,1.630137
4,4,1,2023-06-29 11:27:35,2023-06-29 10:48:37,1.0,0.36,1.0,N,199,257,Credit Card,0.0,5.788000,0.0,1.0,2.500000,1.630137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1495,1,2023-06-29 08:20:22,2023-06-29 08:31:07,1.0,1.23,1.0,N,209,117,Cash,0.0,4.483462,0.0,1.0,2.500000,1.630137
1496,1496,1,2023-06-30 01:06:59,2023-06-30 00:23:03,1.0,0.72,1.0,N,108,64,unknown,1.0,0.084438,0.0,1.0,2.417479,1.630137
1497,1497,0,2023-06-30 08:59:54,2023-06-30 09:44:54,1.0,1.40,1.0,N,37,259,Credit Card,2.5,2.558342,0.0,1.0,2.500000,1.630137
1498,1498,0,2023-06-30 03:15:26,2023-06-30 05:26:08,1.0,1.50,99.0,N,139,72,Credit Card,0.0,2.049960,0.0,1.0,2.417479,1.630137
1499,1499,1,2023-06-30 04:42:05,2023-06-30 03:28:38,1.0,0.56,1.0,N,55,155,Credit Card,1.0,4.181442,0.0,1.0,2.500000,1.630137

In [15]:
test_df['store_and_fwd_flag ']=test_df['store_and_fwd_flag'].replace(0,'N')
test_df['store_and_fwd_flag '].unique()

array(['N', 'Y'], dtype=object)

# **Descriptive statistics of train_df and test_df**

**train_df**

In [16]:
train_df.describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,extra,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.729100,1.382095,3.679527,1.397600,132.710800,132.33240,1.940950,6.094658,0.664425,0.979490,29.740157,2.451683,1.707646
std,0.444672,0.848437,4.905798,5.884656,75.789597,75.95944,1.945885,4.438894,2.441070,0.200076,26.256398,0.458767,0.115383
min,0.000000,1.000000,0.000000,0.000000,1.000000,1.00000,-7.500000,0.000713,-26.550000,-1.000000,-129.300000,-2.500000,-1.750000
25%,0.000000,1.000000,1.070000,1.000000,67.000000,68.00000,0.000000,3.466789,0.000000,1.000000,16.300000,2.500000,1.707646
50%,1.000000,1.000000,1.820000,1.000000,133.000000,132.00000,1.750000,5.208233,0.000000,1.000000,21.360000,2.500000,1.707646
75%,1.000000,1.382095,3.630000,1.000000,198.000000,199.00000,2.500000,7.455228,0.000000,1.000000,31.800000,2.500000,1.707646
max,2.000000,6.000000,71.940000,99.000000,264.000000,264.00000,11.750000,84.032617,32.050000,1.000000,551.000000,2.500000,1.750000

**test_df**

In [17]:
test_df.describe()

,id,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,extra,tip_amount,tolls_amount,improvement_surcharge,congestion_surcharge,Airport_fee
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,749.500000,0.724000,1.380851,3.774533,1.625333,131.562667,131.780000,1.935500,6.132381,0.620073,0.966867,2.417479,1.630137
std,433.157015,0.448655,0.852138,4.895958,7.579749,76.375766,76.044189,2.012937,4.102919,2.187539,0.252860,0.600713,0.198649
min,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,-5.000000,0.001095,-6.550000,-1.000000,-2.500000,-1.750000
25%,374.750000,0.000000,1.000000,1.137500,1.000000,68.000000,65.000000,0.000000,3.545985,0.000000,1.000000,2.500000,1.630137
50%,749.500000,1.000000,1.000000,1.880000,1.000000,131.000000,130.000000,1.000000,5.227615,0.000000,1.000000,2.500000,1.630137
75%,1124.250000,1.000000,1.380851,3.902500,1.000000,200.000000,198.000000,2.500000,7.605167,0.000000,1.000000,2.500000,1.630137
max,1499.000000,2.000000,6.000000,45.490000,99.000000,264.000000,264.000000,11.750000,26.711745,29.560000,1.000000,2.500000,1.750000