In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df=pd.read_csv("/kaggle/input/spam-csv/spam (1).csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [4]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
x_train_count

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 55630 stored elements and shape (4179, 7458)>

In [8]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB() 
model.fit(x_train_count,y_train)

MultinomialNB()

In [9]:
emails=['Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [10]:
x_test

2508                                               Yup...
2875    Crucify is c not s. You should have told me ea...
1086    FR'NDSHIP is like a needle of a clock. Though ...
2156                       What year. And how many miles.
1463    09066362231 URGENT! Your mobile No 07xxxxxxxxx...
                              ...
5285    URGENT! You have won a 1 week FREE membership ...
3699         S:)but he had some luck.2 catches put down:)
1205    WIN a year supply of CDs 4 a store of ur choic...
5058    Hey next sun 1030 there's a basic yoga course....
4902         Taka lor. Wat time u wan 2 come n look 4 us?
Name: Message, Length: 1393, dtype: object

In [11]:
x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

0.9849246231155779

# **Sklearn Pipeline**

In [12]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [13]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [14]:
clf.score(x_test,y_test)

0.9849246231155779

In [15]:
clf.predict(emails)

array([0, 1])